### PR TITLE
Correcting typo in the last paragraph

### PR DESCRIPTION
**Pull request by kenny1986**
Replace "Mac" to "Windows"

### CODE REVIEW

**Comment by SvenDowideit** [comment]
LGTM, bar the signage

**Comment by kenny1986** [comment]
signed.

**Comment by thaJeztah** [comment]
Thanks! LGTM

ping @moxiegirl @SvenDowideit for the merge

**Comment by moxiegirl** [comment]
LGTM thank you @kenny1986

**Pull request merged**
