### PR TITLE
Remove password from shell command

### PR DESCRIPTION
**Pull request by morninj**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks! LGTM

(also, closes https://github.com/docker/docker/issues/16384)

ping @SvenDowideit @moxiegirl

**Comment by moxiegirl** [comment]
@morninj Thanks for the catch. Can you also update the windows and linux `step_six.md` also?

**Comment by moxiegirl** [comment]
@morninj This needs a squash and rebase --- also a signature.  If you need help and would like us to carry, please let me know. Happy to carry.

**Comment by thaJeztah** [comment]
ping @morninj would you be able to sign-off, squash, and rebase?

**Comment by morninj** [comment]
Done (I think). Sorry for the delay.

**Comment by thaJeztah** [comment]
@morninj aww, looks like that didn't go as planned; I see four commits now in your PR and GitHub shows there are merge conflicts. Do you want to give it another go? Or do you want a maintainer to carry your changes?

**Comment by morninj** [comment]
I'm pretty busy at the moment, so it would be great if a maintainer could carry it. Sorry about that, and thanks!

**Comment by thaJeztah** [comment]
no problem, @morninj I'm on the road at the moment, but I added it to my todo's

**Comment by thaJeztah** [comment]
carried in https://github.com/docker/tutorials/issues/58

**Pull request closed without merging**
