### PR TITLE
fixed a few broken links

### PR DESCRIPTION
**Pull request by PI-Victor**
Signed-off-by: pi-victor <ipalade@redhat.com>

### CODE REVIEW

**Comment by thaJeztah** [comment]
LGTM, thanks!

**Comment by thaJeztah** [comment]
ping @moxiegirl @SvenDowideit for review

**Comment by moxiegirl** [comment]
@PI-Victor Thank you for the contribution! LGTM

**Comment by moxiegirl** [comment]
The doc build is failing due to a link the docs-base. Image. I'll sort that out.

**Comment by PI-Victor** [comment]
thank you for the merge!

**Pull request merged**
