### PR TITLE
Issue #14879 - Fix screenshot for 'fortune' program.

### PR DESCRIPTION
**Pull request by charleswhchan**
Signed-off-by: Charles Chan <charles.wh.chan@gmail.com>

### CODE REVIEW

**Comment by thaJeztah** [comment]
LGTM, thanks!

**Comment by thaJeztah** [comment]
fixes https://github.com/docker/docker/issues/14879

**Comment by thaJeztah** [comment]
Also fixes https://github.com/docker/tutorials/issues/12

**Comment by moxiegirl** [comment]
LGTM. @charleswhchan Thanks for the fix!'

**Pull request merged**
