### PR TITLE
Fixing formatting issues; found a few more

### LINKED ISSUE #31: Formatting error in Linux
Jamison reports:

https://docs.docker.com/linux/step_three/

Immediately below the first image on the "whalesay image" page of the Linux tutorial you have a paragraph that appears to have been formatted as plaintext. That didn't seem right, so I thought I'd let you guys know.

### PR DESCRIPTION
**Pull request by moxiegirl**
Fixing an issue reported in feedback.
Checked remaining files and found a few more had accumulated.

Fixes #31 

Signed-off-by: Mary Anthony <mary@docker.com>

### CODE REVIEW

**Comment by moxiegirl** [comment]
ping  @thaJeztah

**Comment by thaJeztah** [comment]
LGTM (by looking at the code changes; can do a `make docs` if you want me to)

I think this fixes https://github.com/docker/tutorials/issues/31 ?

**Comment by thaJeztah** [comment]
doh! 

ping @moxiegirl for the merge, because I can't , LOL

**Comment by moxiegirl** [comment]
@thaJeztah I have no perms to give you access.  You are in doc-owners so I'm not even sure why you *don't* --- :astonished: Thanks for the quick review

**Comment by thaJeztah** [comment]
@moxiegirl actually, I don't think I'm in docs-owners, so that might be the issue :-)

**Comment by moxiegirl** [comment]
@thaJeztah Gotcha...there aren't any standards for who gets added to new repos and how.  I just assume the membership is the same as `docker/docker` --- or close enough.  I'll send an email to Sam.

**Comment by thaJeztah** [comment]
@moxiegirl no worries, this repo isn't as busy as docker/docker so no big issue, it's just that sometimes I forget which repo I'm in, trying to do something and discover that .. oh cr*p not a maintainer here LOL

**Pull request merged**
