### PR TITLE
Removing duplicate lines

### LINKED ISSUE #52: Duplicate lines in Linux install docs
I was upgrading and decided to try out the `docker run hello-world` example in the Linux docs. I noticed the documentation was longer than the actual output of that command. It looks like the last two chunks were repeated.

### PR DESCRIPTION
**Pull request by nloadholtes**
The documentation has duplicate lines of output compared to the actual output of
the command 'docker run hello-world' (as seen in step 4 of
https://docs.docker.com/linux/step_one/ )

Signed-off-by: Nick Loadholtes <nick@ironboundsoftware.com>

Fixes #53

### CODE REVIEW

**Comment by SvenDowideit** [comment]
LGTM - than you @thaJeztah @moxiegirl

**Comment by thaJeztah** [comment]
LGTM, thanks!

**Comment by nloadholtes** [comment]
Thanks to all of you for all of your work on this awesome project

**Comment by thaJeztah** [comment]
@nloadholtes thank you for contributing, "all of you" now includes "you" :+1:

**Pull request merged**
