### PR TITLE
Small fixes found by linkchecker

### PR DESCRIPTION
**Pull request by SvenDowideit**
Signed-off-by: Sven Dowideit <SvenDowideit@home.org.au>

@moxiegirl

### CODE REVIEW

**Comment by thaJeztah** [comment]
What about doing it the other way round? i.e. rename `started.md` to `index.md` and add an alias for `/mac/started/`

**Comment by moxiegirl** [comment]
@SvenDowideit actually, I want to change tutorials-list to `index.md` Then each `started.md` > `index.md`

**Comment by SvenDowideit** [comment]
@moxiegirl @thaJeztah like this? :) yup, i like that more too

**Comment by thaJeztah** [comment]
yup, I like this more

LGTM

@moxiegirl for the final check :)

**Comment by moxiegirl** [comment]
LGTM.  Thank you gents.

**Pull request merged**
