### PR TITLE
Fix Link in /docs/linux/step_two.md

### PR DESCRIPTION
**Pull request by aditirajagopal**
Corrected the link to /docs/linux/step_three.md

Addresses issue #61

Signed-off-by: Aditi Rajagopal <arajagopal@us.ibm.com>

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks! looks like this is also handled by https://github.com/docker/tutorials/pull/63, which includes the same fix for Windows and Mac

**Comment by thaJeztah** [comment]
Thanks for contributing, @aditirajagopal sorry this PR didn't make it in, but it's appreciated :+1:

**Comment by aditirajagopal** [comment]
@thaJeztah np! if there is anything you'd like me to work on, let me know -- would love to help!

**Comment by thaJeztah** [comment]
Cool! Searching for issues labeled "docs" can be a good starting point; https://github.com/docker/docker/issues?q=is%3Aopen+is%3Aissue+label%3Akind%2Fdocs

Always be sure to check if those issues are still relevant, and if the changes are still needed, if you think such an issue can be closed, feel free to "ping" me or another maintainer.

For larger rewrites, it may be good to ping me or @moxiegirl as well, to check if those changes align with the general plans :smile:

Thanks in advance! And don't hesitate to ask for assistance either on GitHub or in the #docker-dev IRC channel

**Comment by moxiegirl** [comment]
@aditirajagopal If you want a nice challenging project, I have a few I could recommend. I don't usually put those in the issues because, well, they would take a lot of time.  Sometimes, tho, they are more interesting.

**Comment by aditirajagopal** [comment]
@moxiegirl that would be fabulous. I'll try to catch you on IRC tomorrow

**Pull request closed without merging**
