### PR TITLE
Fix formatting of step three point two

### PR DESCRIPTION
**Pull request by thaJeztah**
As reported by Baptiste Darthenay on Twitter

>  https://twitter.com/batisteo/status/660415121957765120
> Baptiste Darthenay ⠵`@batisteo`
> @docker Thx for you great docs! There is a little quirk at the end of point 2 
> https://docs.docker.com/linux/step_three/#step-2-run-the-whalesay-image just under the whale. No pb for Mac.

### CODE REVIEW

**Comment by batisteo** [comment]
Thanks @thaJeztah !

There's an other one too:
> https://twitter.com/batisteo/status/660421971130236928
> Baptiste Darthenay ⠵ `@batisteo`
> @docker Same on point 3 https://docs.docker.com/linux/step_six/  btw ;)

**Comment by thaJeztah** [comment]
@batisteo oh, thanks! I didn't look further, let me update this PR and add that as well :+1:

**Comment by thaJeztah** [comment]
updated! :smile:

**Comment by thaJeztah** [comment]
ping @moxiegirl @SvenDowideit PTAL

**Comment by batisteo** [comment]
@thaJeztah Thank you!!

**Comment by thaJeztah** [comment]
hm, actually, looks like this is already in https://github.com/docker/tutorials/pull/39/files#diff-33760cd3945696128094f2501818d123R32, but not merged yet. LOL

**Comment by SvenDowideit** [comment]
LGTM

**Pull request merged**
